name: "Update Weeklies"
on:
  workflow_dispatch
#  schedule:
#   - cron: "*/5 * * * *"
#   - cron: "0 0 * * 1"
#   - cron: "0 0 * 0 *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          script: |
            import os
            import json
            print("Directory contents:")
            for f in os.listdir("mods/submissions"):
                print(f)
                file = open(f+"/data.txt");
                data = json.load(file);
                for i in data:
                    print(i);
                file.close();
